gui:
  theme:
    activeBorderColor:
      - "#fca7ea"
      - bold
    inactiveBorderColor:
      - "#828bb8"
    selectedLineBgColor:
      - "#2f334d"
    cherryPickedCommitBgColor:
      - "#444a73"
    cherryPickedCommitFgColor:
      - "#fca7ea"
    unstagedChangesColor:
      - "#ff757f"

git:
  paging:
    colorArg: always
    pager: delta --dark --pager "less -RF"